version: "3"

services:
  http:
    build: .
    volumes:
    - "./view/:/var/www/html/view/"
    - "./include/:/var/www/html/include/"
    - "./i18n/:/var/www/html/i18n/"
    - "./bootstrap.php:/var/www/html/bootstrap.php"
    - "./config.php:/var/www/html/config.php"
    - "./index.php:/var/www/html/index.php"
    - "./api.php:/var/www/html/api.php"
    - "./.htaccess.dynamic:/var/www/html/.htaccess"
    - "./html/css/:/var/www/html/css/"
    - "./html/js/:/var/www/html/js/"
    - "./html/img/:/var/www/html/img/"
    - "./source/apache/damavis.conf:/etc/apache2/sites-enabled/damavis.conf"
    ports:
    - "80:80"
