version: "3"

services:
  http:
    build: .
    volumes:
    - "./html/:/var/www/html/"
    - "./img/:/var/www/html/img/:ro"
    - "./css/:/var/www/html/css/:ro"
    - "./js/:/var/www/html/js/:ro"
    - "./.htaccess.static:/var/www/html/.htaccess:ro"
    - "./source/apache/localhost.conf:/etc/apache2/sites-enabled/localhost.conf:ro"
    ports:
    - "80:80"
