version: "3"

services:
  http:
    build: .
    volumes:
    - "./html/:/var/www/html/"
    - "./.htaccess.static:/var/www/html/.htaccess"
    - "./source/apache/damavis.conf:/etc/apache2/sites-enabled/damavis.conf"
    ports:
    - "80:80"
