version: "3"

services:
  http:
    build: .
    volumes:
    - ".:/var/www/html:ro"
    - "./.htaccess.static:/var/www/html/.htaccess:ro"
    - "./source/apache/localhost.conf:/etc/apache2/sites-enabled/localhost.conf:ro"
    ports:
    - "80:80"
